// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/ApplicationUpdate.graphml")
public interface ApplicationUpdate {

    @Vertex()
    void v_Home();

    @Vertex()
    void v_ProjectDetails();

    @Edge()
    void e_SaveAppStatus();

    @Edge()
    void e_PlanningTrigger();

    @Edge()
    void e_ProjectDetailsLoc();

    @Vertex()
    void v_ApplicationStatusUpdate();

    @Vertex()
    void v_Application();

    @Edge()
    void e_DeleteAppStatus();

    @Vertex()
    void v_PlanningTrigger();

    @Edge()
    void e_ApplicationDetail();
}
