// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/CreatePMTProject.graphml")
public interface CreatePMTProject {

    @Edge()
    void e_CorrectData();

    @Edge()
    void e_IncorrectData();

    @Vertex()
    void v_CreatePMTProject();

    @Vertex()
    void v_PMTProject_Status();
}
