// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/Firstapprovalloggin.graphml")
public interface Firstapprovalloggin {

    @Vertex()
    void v_Home();

    @Vertex()
    void v_LoginPrompted();

    @Edge()
    void e_ValidManagerCredentials();
}
