// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/Main_PMTFlow.graphml")
public interface Main_PMTFlow {

    @Vertex()
    void v_SearchPMTProject();

    @Edge()
    void e_houver2PMTProjectstatus();

    @Vertex()
    void v_ApprovePMTProject();

    @Vertex()
    void v_LoginPrompted();

    @Vertex()
    void v_PMTProjectClosure();

    @Vertex()
    void v_BaseUrl();

    @Edge()
    void e_Valid_Manager_Credentials();

    @Edge()
    void e_houver2Searchproject();

    @Vertex()
    void v_Home();

    @Edge()
    void e_houver2SearchProject();

    @Vertex()
    void v_CreatePMTProject();

    @Edge()
    void e_StartClient();

    @Edge()
    void e_hover2Projecttab();

    @Edge()
    void e_Init();

    @Vertex()
    void v_UpdatePMTProject();

    @Edge()
    void e_InvalidCredentials();

    @Vertex()
    void v_PMTLogout();

    @Edge()
    void e_houver2Logout();
}
