// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/PMTProjectApproval.graphml")
public interface PMTProjectApproval {

    @Edge()
    void e_LoginasManager();

    @Edge()
    void e_houver2PMTProjectstatus();

    @Vertex()
    void v_ApprovePMTProject();

    @Edge()
    void e_houver2Logout();

    @Vertex()
    void v_PMTLogout();

    @Vertex()
    void v_PMTProject_Status();

    @Vertex()
    void v_ApproveProject();

    @Edge()
    void e_LoginasDirector();
}
