// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/PMTProjectClosure.graphml")
public interface PMTProjectClosure {

    @Vertex()
    void v_SearchPMTProject();

    @Edge()
    void e_houver2Logout();

    @Vertex()
    void v_PMTProjectClosure();

    @Vertex()
    void v_PerformProjectClosure();

    @Vertex()
    void v_PMTLogout();

    @Edge()
    void e_hover2Detaills();

    @Edge()
    void e_houver2Searchproject();
}
