// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/PMTSearchProject.graphml")
public interface PMTSearchProject {

    @Vertex()
    void v_ProjectPagedisplayed();

    @Vertex()
    void v_SearchPMTProject();

    @Edge()
    void e_clickonProject();
}
