// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/Projectapproval.graphml")
public interface Projectapproval {

    @Vertex()
    void v_Home();

    @Vertex()
    void v_logout();

    @Vertex()
    void v_Pending_Workflow_Task();

    @Vertex()
    void v_Approve_Pendingproject();

    @Edge()
    void e_Pending_task();

    @Edge()
    void e_Hover2Project();

    @Vertex()
    void v_Nopending_Workflow_Task();

    @Edge()
    void e_Approval_Reason();
}
