// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/ProjectCreate.graphml")
public interface ProjectCreate {

    @Edge()
    void e_EnterAllRequiredDetail();

    @Vertex()
    void v_Project();

    @Vertex()
    void v_CreateProject();

    @Edge()
    void e_ProjectDetailsLoc();

    @Vertex()
    void v_SubmitProject();
}
