// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/ReportIssue.graphml")
public interface ReportIssue {

    @Edge()
    void e_LogoutSharePoint();

    @Edge()
    void e_SubmitIssue();

    @Edge()
    void e_AddItem();

    @Vertex()
    void v_PmtIssueTracker();

    @Vertex()
    void v_IssueAdded();

    @Vertex()
    void v_ReportIssue();
}
