// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/SearchProject.graphml")
public interface SearchProject {

    @Edge()
    void e_ProjectDetailsLoc();

    @Vertex()
    void v_Search_Project();

    @Vertex()
    void v_Search_flow();
}
