// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/Test4.graphml")
public interface Test4 {

    @Edge()
    void e_hover2update_Project();

    @Vertex()
    void v_SearchPMTProject();

    @Vertex()
    void v_UpdatePMTProject();
}
