// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/Test3.graphml")
public interface Test3 {

    @Edge()
    void e_hover2ProjectTask();

    @Vertex()
    void v_SearchPMTProject();

    @Edge()
    void e_hover2SearchProject();

    @Vertex()
    void v_ApprovePMTProject();

    @Vertex()
    void v_PMTProject_Status();
}
