// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/Test1.graphml")
public interface Test1 {

    @Vertex()
    void v_Home();

    @Vertex()
    void v_LoginPrompted();

    @Vertex()
    void v_BaseUrl();

    @Vertex()
    void v_CreatePMTProject();

    @Edge()
    void e_StartClient();

    @Edge()
    void e_hover2Projecttab();

    @Edge()
    void e_Init();

    @Edge()
    void e_Valid_Manager_Credentials();

    @Edge()
    void e_InvalidCredentials();
}
