// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/Test5.graphml")
public interface Test5 {

    @Vertex()
    void v_ApplicationUpdate();

    @Vertex()
    void v_ResourceUpdate();

    @Edge()
    void e_hover2Projectclosure();

    @Vertex()
    void v_PMTProjectClosure();

    @Edge()
    void e_hover2link();

    @Edge()
    void e_hover2resouce();

    @Vertex()
    void v_DetailsUpdate();

    @Edge()
    void e_hover2Detaills();

    @Edge()
    void e_hover2Application();

    @Vertex()
    void v_LinkUpdate();

    @Vertex()
    void v_UpdatePMTProject();
}
