// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/Test2.graphml")
public interface Test2 {

    @Edge()
    void e_CorrectData();

    @Edge()
    void e_IncorrectData();

    @Edge()
    void e_houver2PMTProjectstatus();

    @Vertex()
    void v_CreatePMTProject();

    @Vertex()
    void v_PMTProject_Status();

    @Vertex()
    void v_PMTProjectCreated();
}
