// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/UpdateProject.graphml")
public interface UpdateProject {

    @Vertex()
    void v_Adding_resouces();

    @Edge()
    void e_Risk_link();

    @Edge()
    void e_Resources_link();

    @Vertex()
    void v_Adding_applicationdetails();

    @Edge()
    void e_Application_link();

    @Vertex()
    void v_Adding_dependency();

    @Edge()
    void e_Dependency_link();

    @Vertex()
    void v_Adding_risks();

    @Vertex()
    void v_Search_Project();

    @Vertex()
    void v_Project_closure();
}
