// Generated by GraphWalker (http://www.graphwalker.org)
package ctl.graphwalker.pmt.test;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "ctl/graphwalker/pmt/UpdatePMTProject.graphml")
public interface UpdatePMTProject {

    @Vertex()
    void v_ApplicationUpdate();

    @Vertex()
    void v_SearchPMTProject();

    @Vertex()
    void v_DetailsUpdate();

    @Vertex()
    void v_PMTLogout();

    @Vertex()
    void v_LinkUpdate();

    @Edge()
    void e_houver2Searchproject();

    @Vertex()
    void v_ResourceUpdate();

    @Edge()
    void e_houver2Logout();

    @Edge()
    void e_hover2link();

    @Edge()
    void e_hover2resouce();

    @Edge()
    void e_hover2Detaills();

    @Edge()
    void e_hover2Application();

    @Vertex()
    void v_UpdatePMTProject();
}
